<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Model Registry
    |--------------------------------------------------------------------------
    |
    | This file contains the complete registry of all models available in the
    | LLM Resayil platform. All 45 models (15 local + 30 cloud proxies) are
    | listed with their metadata, pricing, and Ollama name mappings.
    |
    | Cloud models use the `:cloud` suffix internally for the Ollama proxy
    | server at http://208.110.93.90:11434.
    |
    */

    'default_credit_multiplier' => 1.0,

    'models' => [
        // ============================================================================
        // LOCAL MODELS (15 models) - 1 credit per token
        // ============================================================================

        'llama3.2:3b' => [
            'name' => 'Llama 3.2 3B',
            'family' => 'Llama 3',
            'type' => 'local',
            'category' => 'chat',
            'size' => 'small',
            'context_window' => 16384,
            'description' => 'Lightweight 3B parameter model for fast inference',
            'license' => 'llama3',
            'params' => '3B',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'llama3.2:3b',
            'credit_multiplier' => 0.5,
            'is_active' => true,
        ],

        'smollm2:135m' => [
            'name' => 'SmallLM 2 135M',
            'family' => 'SmallLM',
            'type' => 'local',
            'category' => 'chat',
            'size' => 'small',
            'context_window' => 8192,
            'description' => 'Tiny 135M parameter model for quick tasks',
            'license' => 'apache-2.0',
            'params' => '135M',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'smollm2:135m',
            'credit_multiplier' => 0.5,
            'is_active' => true,
        ],

        'qwen2.5-coder:14b' => [
            'name' => 'Qwen 2.5 Coder 14B',
            'family' => 'Qwen',
            'type' => 'local',
            'category' => 'code',
            'size' => 'medium',
            'context_window' => 32768,
            'description' => 'Code-focused model with 14B parameters',
            'license' => 'apache-2.0',
            'params' => '14B',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'qwen2.5-coder:14b',
            'credit_multiplier' => 1.5,
            'is_active' => true,
        ],

        'mistral-small3.2:24b' => [
            'name' => 'Mistral Small 3.2 24B',
            'family' => 'Mistral',
            'type' => 'local',
            'category' => 'chat',
            'size' => 'medium',
            'context_window' => 32768,
            'description' => 'High-performance 24B parameter model',
            'license' => 'apache-2.0',
            'params' => '24B',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'mistral-small3.2:24b-instruct-2506-q4_K_M',
            'credit_multiplier' => 1.5,
            'is_active' => true,
        ],

        'phi3.5-mini:3.8b' => [
            'name' => 'Phi 3.5 Mini 3.8B',
            'family' => 'Phi',
            'type' => 'local',
            'category' => 'chat',
            'size' => 'small',
            'context_window' => 128000,
            'description' => 'Small model with large context window',
            'license' => 'mit',
            'params' => '3.8B',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'phi3.5:mini',
            'credit_multiplier' => 0.5,
            'is_active' => true,
        ],

        'gemma2:9b' => [
            'name' => 'Gemma 2 9B',
            'family' => 'Gemma',
            'type' => 'local',
            'category' => 'chat',
            'size' => 'medium',
            'context_window' => 8192,
            'description' => 'Google Gemma 2 with 9B parameters',
            'license' => 'gemma',
            'params' => '9B',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'gemma2:9b',
            'credit_multiplier' => 1.5,
            'is_active' => true,
        ],

        'deepseek-coder:6.7b' => [
            'name' => 'DeepSeek Coder 6.7B',
            'family' => 'DeepSeek',
            'type' => 'local',
            'category' => 'code',
            'size' => 'medium',
            'context_window' => 16384,
            'description' => 'Code-focused model with 6.7B parameters',
            'license' => 'agpl-3.0',
            'params' => '6.7B',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'deepseek-coder:6.7b',
            'credit_multiplier' => 1.5,
            'is_active' => true,
        ],

        'llama3.1:8b' => [
            'name' => 'Llama 3.1 8B',
            'family' => 'Llama 3',
            'type' => 'local',
            'category' => 'chat',
            'size' => 'medium',
            'context_window' => 128000,
            'description' => 'Versatile 8B parameter model',
            'license' => 'llama3',
            'params' => '8B',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'llama3.1:8b',
            'credit_multiplier' => 1.5,
            'is_active' => true,
        ],

        'nomic-embed-text' => [
            'name' => 'Nomic Embed Text',
            'family' => 'Nomic',
            'type' => 'local',
            'category' => 'embedding',
            'size' => 'small',
            'context_window' => 8192,
            'description' => 'Text embedding model',
            'license' => 'mit',
            'params' => '110M',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'nomic-embed-text',
            'credit_multiplier' => 0.5,
            'is_active' => true,
        ],

        'bge-m3' => [
            'name' => 'BGE M3',
            'family' => 'BGE',
            'type' => 'local',
            'category' => 'embedding',
            'size' => 'medium',
            'context_window' => 8192,
            'description' => 'Dense, sparse, and multi-quantizer embeddings',
            'license' => 'mit',
            'params' => '580M',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'bge-m3',
            'credit_multiplier' => 1.5,
            'is_active' => true,
        ],

        'all-minilm' => [
            'name' => 'All-MiniLM',
            'family' => 'All-MiniLM',
            'type' => 'local',
            'category' => 'embedding',
            'size' => 'small',
            'context_window' => 512,
            'description' => 'Lightweight embedding model',
            'license' => 'apache-2.0',
            'params' => '23M',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'all-minilm',
            'credit_multiplier' => 0.5,
            'is_active' => true,
        ],

        'snowflake-arctic-embed' => [
            'name' => 'Snowflake Arctic Embed',
            'family' => 'Snowflake',
            'type' => 'local',
            'category' => 'embedding',
            'size' => 'medium',
            'context_window' => 512,
            'description' => 'High-quality embedding model',
            'license' => 'apache-2.0',
            'params' => '137M',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'snowflake-arctic-embed',
            'credit_multiplier' => 1.5,
            'is_active' => true,
        ],

        'mistral-7b' => [
            'name' => 'Mistral 7B',
            'family' => 'Mistral',
            'type' => 'local',
            'category' => 'chat',
            'size' => 'medium',
            'context_window' => 32768,
            'description' => 'Original Mistral with 7B parameters',
            'license' => 'apache-2.0',
            'params' => '7B',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'mistral:7b',
            'credit_multiplier' => 1.5,
            'is_active' => true,
        ],

        'starcoder2:3b' => [
            'name' => 'StarCoder 2 3B',
            'family' => 'StarCoder',
            'type' => 'local',
            'category' => 'code',
            'size' => 'small',
            'context_window' => 16384,
            'description' => 'Code generation model',
            'license' => 'apache-2.0',
            'params' => '3B',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'starcoder2:3b',
            'credit_multiplier' => 0.5,
            'is_active' => true,
        ],

        'codellama:7b' => [
            'name' => 'CodeLlama 7B',
            'family' => 'CodeLlama',
            'type' => 'local',
            'category' => 'code',
            'size' => 'small',
            'context_window' => 16384,
            'description' => 'Code-specific Llama model',
            'license' => 'llama',
            'params' => '7B',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'codellama:7b',
            'credit_multiplier' => 0.5,
            'is_active' => true,
        ],

        // ============================================================================
        // CLOUD PROXY MODELS (30 models) - 2 credits per token
        // These are proxied through ollama.com
        // ============================================================================

        // Enterprise Tier - Large Models
        'glm-4.7-flash' => [
            'name' => 'GLM-4.7 Flash',
            'family' => 'GLM',
            'type' => 'cloud',
            'category' => 'vision',
            'size' => 'medium',
            'context_window' => 128000,
            'description' => 'Zhipu AI multimodal model',
            'license' => 'proprietary',
            'params' => '12B',
            'quantization' => 'FP16',
            'ollama_name' => 'glm-4.7-flash:cloud',
            'credit_multiplier' => 2.5,
            'is_active' => true,
        ],

        'qwen3-30b' => [
            'name' => 'Qwen 3 30B',
            'family' => 'Qwen',
            'type' => 'cloud',
            'category' => 'thinking',
            'size' => 'medium',
            'context_window' => 32768,
            'description' => 'Qwen 3 with 30B parameters',
            'license' => 'apache-2.0',
            'params' => '30B',
            'quantization' => 'FP16',
            'ollama_name' => 'qwen3-30b:cloud',
            'credit_multiplier' => 2.5,
            'is_active' => true,
        ],

        'gpt-oss:20b' => [
            'name' => 'GPT OSS 20B',
            'family' => 'GPT',
            'type' => 'cloud',
            'category' => 'chat',
            'size' => 'medium',
            'context_window' => 128000,
            'description' => 'OpenAI open source model',
            'license' => 'mit',
            'params' => '20B',
            'quantization' => 'FP16',
            'ollama_name' => 'gpt-oss:20b-cloud',
            'credit_multiplier' => 2.5,
            'is_active' => true,
        ],

        'Qwen3-VL-32B' => [
            'name' => 'Qwen3-VL 32B',
            'family' => 'Qwen',
            'type' => 'cloud',
            'category' => 'vision',
            'size' => 'large',
            'context_window' => 128000,
            'description' => 'Qwen3 Vision-Language model',
            'license' => 'apache-2.0',
            'params' => '32B',
            'quantization' => 'FP16',
            'ollama_name' => 'qwen3-vl:32b-cloud',
            'credit_multiplier' => 3.5,
            'is_active' => true,
        ],

        // Cloud Models via ollama.com (4 exclusive models)
        'qwen3.5:397b' => [
            'name' => 'Qwen 3.5 397B',
            'family' => 'Qwen',
            'type' => 'cloud',
            'category' => 'thinking',
            'size' => 'large',
            'context_window' => 32768,
            'description' => 'Qwen 3.5 with 397B parameters (MoE)',
            'license' => 'apache-2.0',
            'params' => '397B',
            'quantization' => 'FP16',
            'ollama_name' => 'qwen3.5:cloud',
            'credit_multiplier' => 3.5,
            'is_active' => true,
        ],

        'devstral-2:123b' => [
            'name' => 'Devstral 2 123B',
            'family' => 'Devstral',
            'type' => 'cloud',
            'category' => 'code',
            'size' => 'large',
            'context_window' => 128000,
            'description' => 'Mistral Devstral 2 with 123B parameters',
            'license' => 'proprietary',
            'params' => '123B',
            'quantization' => 'FP16',
            'ollama_name' => 'devstral-2:123b-cloud',
            'credit_multiplier' => 3.5,
            'is_active' => true,
        ],

        'deepseek-v3.1:671b' => [
            'name' => 'DeepSeek V3.1 671B',
            'family' => 'DeepSeek',
            'type' => 'cloud',
            'category' => 'thinking',
            'size' => 'large',
            'context_window' => 128000,
            'description' => 'DeepSeek V3.1 with 671B parameters',
            'license' => 'agpl-3.0',
            'params' => '671B',
            'quantization' => 'FP16',
            'ollama_name' => 'deepseek-v3.1:671b-cloud',
            'credit_multiplier' => 3.5,
            'is_active' => true,
        ],

        'deepseek-v3.2' => [
            'name' => 'DeepSeek V3.2',
            'family' => 'DeepSeek',
            'type' => 'cloud',
            'category' => 'thinking',
            'size' => 'large',
            'context_window' => 128000,
            'description' => 'DeepSeek V3.2 latest version',
            'license' => 'agpl-3.0',
            'params' => '671B',
            'quantization' => 'FP16',
            'ollama_name' => 'deepseek-v3.2:cloud',
            'credit_multiplier' => 3.5,
            'is_active' => true,
        ],

        // Additional Cloud Models (26 more from ollama.com)
        'llama3.2:11b' => [
            'name' => 'Llama 3.2 11B',
            'family' => 'Llama 3',
            'type' => 'cloud',
            'category' => 'vision',
            'size' => 'medium',
            'context_window' => 16384,
            'description' => 'Llama 3.2 with 11B parameters',
            'license' => 'llama3',
            'params' => '11B',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'llama3.2:11b-cloud',
            'credit_multiplier' => 2.5,
            'is_active' => true,
        ],

        'llama3.2:70b' => [
            'name' => 'Llama 3.2 70B',
            'family' => 'Llama 3',
            'type' => 'cloud',
            'category' => 'chat',
            'size' => 'large',
            'context_window' => 16384,
            'description' => 'Llama 3.2 with 70B parameters',
            'license' => 'llama3',
            'params' => '70B',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'llama3.2:70b-cloud',
            'credit_multiplier' => 3.5,
            'is_active' => true,
        ],

        'llama3.1:70b' => [
            'name' => 'Llama 3.1 70B',
            'family' => 'Llama 3',
            'type' => 'cloud',
            'category' => 'chat',
            'size' => 'large',
            'context_window' => 128000,
            'description' => 'Llama 3.1 with 70B parameters',
            'license' => 'llama3',
            'params' => '70B',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'llama3.1:70b-cloud',
            'credit_multiplier' => 3.5,
            'is_active' => true,
        ],

        'llama3.1:405b' => [
            'name' => 'Llama 3.1 405B',
            'family' => 'Llama 3',
            'type' => 'cloud',
            'category' => 'chat',
            'size' => 'large',
            'context_window' => 128000,
            'description' => 'Llama 3.1 with 405B parameters (MoE)',
            'license' => 'llama3',
            'params' => '405B',
            'quantization' => 'FP16',
            'ollama_name' => 'llama3.1:405b-cloud',
            'credit_multiplier' => 3.5,
            'is_active' => true,
        ],

        'gemma2:27b' => [
            'name' => 'Gemma 2 27B',
            'family' => 'Gemma',
            'type' => 'cloud',
            'category' => 'chat',
            'size' => 'large',
            'context_window' => 8192,
            'description' => 'Google Gemma 2 with 27B parameters',
            'license' => 'gemma',
            'params' => '27B',
            'quantization' => 'FP16',
            'ollama_name' => 'gemma2:27b-cloud',
            'credit_multiplier' => 3.5,
            'is_active' => true,
        ],

        'mixtral:8x7b' => [
            'name' => 'Mixtral 8x7B',
            'family' => 'Mixtral',
            'type' => 'cloud',
            'category' => 'chat',
            'size' => 'large',
            'context_window' => 32768,
            'description' => 'Mistral Mixtral 8x7B MoE',
            'license' => 'apache-2.0',
            'params' => '8x7B',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'mixtral:8x7b-cloud',
            'credit_multiplier' => 3.5,
            'is_active' => true,
        ],

        'mixtral:8x22b' => [
            'name' => 'Mixtral 8x22B',
            'family' => 'Mixtral',
            'type' => 'cloud',
            'category' => 'chat',
            'size' => 'large',
            'context_window' => 65536,
            'description' => 'Mistral Mixtral 8x22B MoE',
            'license' => 'apache-2.0',
            'params' => '8x22B',
            'quantization' => 'FP16',
            'ollama_name' => 'mixtral:8x22b-cloud',
            'credit_multiplier' => 3.5,
            'is_active' => true,
        ],

        'mistral-large:24b' => [
            'name' => 'Mistral Large 24B',
            'family' => 'Mistral',
            'type' => 'cloud',
            'category' => 'chat',
            'size' => 'medium',
            'context_window' => 32768,
            'description' => 'Mistral Large with 24B parameters',
            'license' => 'proprietary',
            'params' => '24B',
            'quantization' => 'FP16',
            'ollama_name' => 'mistral-large:24b-cloud',
            'credit_multiplier' => 2.5,
            'is_active' => true,
        ],

        'mistral-nemo:12b' => [
            'name' => 'Mistral Nemo 12B',
            'family' => 'Mistral',
            'type' => 'cloud',
            'category' => 'chat',
            'size' => 'medium',
            'context_window' => 128000,
            'description' => 'Mistral Nemo with 12B parameters',
            'license' => 'apache-2.0',
            'params' => '12B',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'mistral-nemo:12b-cloud',
            'credit_multiplier' => 2.5,
            'is_active' => true,
        ],

        'codestral:22b' => [
            'name' => 'Codestral 22B',
            'family' => 'Mistral',
            'type' => 'cloud',
            'category' => 'code',
            'size' => 'medium',
            'context_window' => 32768,
            'description' => 'Mistral Codestral for code generation',
            'license' => 'apache-2.0',
            'params' => '22B',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'codestral:22b-cloud',
            'credit_multiplier' => 2.5,
            'is_active' => true,
        ],

        'deepseek-coder:33b' => [
            'name' => 'DeepSeek Coder 33B',
            'family' => 'DeepSeek',
            'type' => 'cloud',
            'category' => 'code',
            'size' => 'large',
            'context_window' => 16384,
            'description' => 'DeepSeek Coder with 33B parameters',
            'license' => 'agpl-3.0',
            'params' => '33B',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'deepseek-coder:33b-cloud',
            'credit_multiplier' => 3.5,
            'is_active' => true,
        ],

        'deepseek-chat:671b' => [
            'name' => 'DeepSeek Chat 671B',
            'family' => 'DeepSeek',
            'type' => 'cloud',
            'category' => 'thinking',
            'size' => 'large',
            'context_window' => 128000,
            'description' => 'DeepSeek Chat with 671B parameters',
            'license' => 'agpl-3.0',
            'params' => '671B',
            'quantization' => 'FP16',
            'ollama_name' => 'deepseek-chat:671b-cloud',
            'credit_multiplier' => 3.5,
            'is_active' => true,
        ],

        'qwen2:72b' => [
            'name' => 'Qwen 2 72B',
            'family' => 'Qwen',
            'type' => 'cloud',
            'category' => 'chat',
            'size' => 'large',
            'context_window' => 32768,
            'description' => 'Qwen 2 with 72B parameters',
            'license' => 'apache-2.0',
            'params' => '72B',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'qwen2:72b-cloud',
            'credit_multiplier' => 3.5,
            'is_active' => true,
        ],

        'qwen2.5:32b' => [
            'name' => 'Qwen 2.5 32B',
            'family' => 'Qwen',
            'type' => 'cloud',
            'category' => 'chat',
            'size' => 'large',
            'context_window' => 128000,
            'description' => 'Qwen 2.5 with 32B parameters',
            'license' => 'apache-2.0',
            'params' => '32B',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'qwen2.5:32b-cloud',
            'credit_multiplier' => 3.5,
            'is_active' => true,
        ],

        'yi:34b' => [
            'name' => 'Yi 34B',
            'family' => 'Yi',
            'type' => 'cloud',
            'category' => 'chat',
            'size' => 'large',
            'context_window' => 16384,
            'description' => '01.AI Yi with 34B parameters',
            'license' => 'proprietary',
            'params' => '34B',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'yi:34b-cloud',
            'credit_multiplier' => 3.5,
            'is_active' => true,
        ],

        'deepseek-v2.5' => [
            'name' => 'DeepSeek V2.5',
            'family' => 'DeepSeek',
            'type' => 'cloud',
            'category' => 'thinking',
            'size' => 'large',
            'context_window' => 128000,
            'description' => 'DeepSeek V2.5 with MoE architecture',
            'license' => 'agpl-3.0',
            'params' => '236B',
            'quantization' => 'FP16',
            'ollama_name' => 'deepseek-v2.5:cloud',
            'credit_multiplier' => 3.5,
            'is_active' => true,
        ],

        'llama3-gradient:70b' => [
            'name' => 'Llama 3 Gradient 70B',
            'family' => 'Llama 3',
            'type' => 'cloud',
            'category' => 'chat',
            'size' => 'large',
            'context_window' => 262144,
            'description' => 'Llama 3 with extended context',
            'license' => 'llama3',
            'params' => '70B',
            'quantization' => 'FP16',
            'ollama_name' => 'llama3-gradient:70b-cloud',
            'credit_multiplier' => 3.5,
            'is_active' => true,
        ],

        'command-r:35b' => [
            'name' => 'Command R 35B',
            'family' => 'Cohere',
            'type' => 'cloud',
            'category' => 'tools',
            'size' => 'large',
            'context_window' => 128000,
            'description' => 'Cohere Command R for RAG',
            'license' => 'apache-2.0',
            'params' => '35B',
            'quantization' => 'FP16',
            'ollama_name' => 'command-r:35b-cloud',
            'credit_multiplier' => 3.5,
            'is_active' => true,
        ],

        'command-r-plus:104b' => [
            'name' => 'Command R+ 104B',
            'family' => 'Cohere',
            'type' => 'cloud',
            'category' => 'tools',
            'size' => 'large',
            'context_window' => 128000,
            'description' => 'Cohere Command R+ for advanced RAG',
            'license' => 'apache-2.0',
            'params' => '104B',
            'quantization' => 'FP16',
            'ollama_name' => 'command-r-plus:104b-cloud',
            'credit_multiplier' => 3.5,
            'is_active' => true,
        ],

        'firefunction-v2:18b' => [
            'name' => 'FireFunction v2 18B',
            'family' => 'Fireworks',
            'type' => 'cloud',
            'category' => 'tools',
            'size' => 'medium',
            'context_window' => 8192,
            'description' => 'Fireworks FireFunction for function calling',
            'license' => 'proprietary',
            'params' => '18B',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'firefunction-v2:18b-cloud',
            'credit_multiplier' => 2.5,
            'is_active' => true,
        ],

        'nomic-embed:27m' => [
            'name' => 'Nomic Embed 27M',
            'family' => 'Nomic',
            'type' => 'cloud',
            'category' => 'embedding',
            'size' => 'small',
            'context_window' => 8192,
            'description' => 'Nomic Embed for text embeddings',
            'license' => 'mit',
            'params' => '27M',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'nomic-embed:27m-cloud',
            'credit_multiplier' => 1.0,
            'is_active' => true,
        ],

        'gte-qwen:7m' => [
            'name' => 'GTE Qwen 7M',
            'family' => 'GTE',
            'type' => 'cloud',
            'category' => 'embedding',
            'size' => 'small',
            'context_window' => 32768,
            'description' => 'GTE Qwen embedding model',
            'license' => 'apache-2.0',
            'params' => '7M',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'gte-qwen:7m-cloud',
            'credit_multiplier' => 1.0,
            'is_active' => true,
        ],

        'bge-large:335m' => [
            'name' => 'BGE Large 335M',
            'family' => 'BGE',
            'type' => 'cloud',
            'category' => 'embedding',
            'size' => 'medium',
            'context_window' => 512,
            'description' => 'BGE Large embedding model',
            'license' => 'mit',
            'params' => '335M',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'bge-large:335m-cloud',
            'credit_multiplier' => 2.5,
            'is_active' => true,
        ],

        'e5-mistral:7b' => [
            'name' => 'E5 Mistral 7B',
            'family' => 'E5',
            'type' => 'cloud',
            'category' => 'embedding',
            'size' => 'medium',
            'context_window' => 512,
            'description' => 'E5 Mistral embedding model',
            'license' => 'apache-2.0',
            'params' => '7B',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'e5-mistral:7b-cloud',
            'credit_multiplier' => 2.5,
            'is_active' => true,
        ],

        'nvidia-embed:1b' => [
            'name' => 'NVIDIA Embed 1B',
            'family' => 'NVIDIA',
            'type' => 'cloud',
            'category' => 'embedding',
            'size' => 'small',
            'context_window' => 512,
            'description' => 'NVIDIA NeMo Embedding model',
            'license' => 'proprietary',
            'params' => '1B',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'nvidia-embed:1b-cloud',
            'credit_multiplier' => 1.0,
            'is_active' => true,
        ],

        'all-minilm-l6:22m' => [
            'name' => 'All-MiniLM L6 22M',
            'family' => 'All-MiniLM',
            'type' => 'cloud',
            'category' => 'embedding',
            'size' => 'small',
            'context_window' => 512,
            'description' => 'All-MiniLM L6 v2 embedding model',
            'license' => 'apache-2.0',
            'params' => '22M',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'all-minilm-l6:22m-cloud',
            'credit_multiplier' => 1.0,
            'is_active' => true,
        ],

        'gte-base:110m' => [
            'name' => 'GTE Base 110M',
            'family' => 'GTE',
            'type' => 'cloud',
            'category' => 'embedding',
            'size' => 'small',
            'context_window' => 512,
            'description' => 'GTE Base embedding model',
            'license' => 'apache-2.0',
            'params' => '110M',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'gte-base:110m-cloud',
            'credit_multiplier' => 1.0,
            'is_active' => true,
        ],

        'snowflake-arctic-embed-l:335m' => [
            'name' => 'Snowflake Arctic Embed L 335M',
            'family' => 'Snowflake',
            'type' => 'cloud',
            'category' => 'embedding',
            'size' => 'medium',
            'context_window' => 512,
            'description' => 'Snowflake Arctic Embed Large',
            'license' => 'apache-2.0',
            'params' => '335M',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'snowflake-arctic-embed-l:335m-cloud',
            'credit_multiplier' => 2.5,
            'is_active' => true,
        ],

        'bge-small:8m' => [
            'name' => 'BGE Small 8M',
            'family' => 'BGE',
            'type' => 'cloud',
            'category' => 'embedding',
            'size' => 'small',
            'context_window' => 512,
            'description' => 'BGE Small embedding model',
            'license' => 'mit',
            'params' => '8M',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'bge-small:8m-cloud',
            'credit_multiplier' => 1.0,
            'is_active' => true,
        ],

        'minilm-l12:39m' => [
            'name' => 'MiniLM L12 39M',
            'family' => 'MiniLM',
            'type' => 'cloud',
            'category' => 'embedding',
            'size' => 'small',
            'context_window' => 512,
            'description' => 'MiniLM L12 embedding model',
            'license' => 'apache-2.0',
            'params' => '39M',
            'quantization' => 'Q4_K_M',
            'ollama_name' => 'minilm-l12:39m-cloud',
            'credit_multiplier' => 1.0,
            'is_active' => true,
        ],
    ],
];
